# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-175085-administrator-Precision-3660/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tsbg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/sdc
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/f0b6/hdl/verilog
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/35de/hdl/verilog
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/c2c6
  } {
      /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/sdc
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/f0b6/hdl/verilog
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/35de/hdl/verilog
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/c2c6
  } {
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_axi_smc_1_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_mem_reset_control_0_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_mig_7series_0_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_Ethernet_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_SD_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_UART_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_XADC_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_ethernet_stream_0_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_io_axi_m_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_io_axi_s_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_axi_gpio_0_1_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_RocketChip_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_clk_wiz_0_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_util_vector_logic_0_0_stub.v
      ./.Xil/Vivado-175085-administrator-Precision-3660/realtime/riscv_rst_clk_wiz_0_50M_5_stub.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/board/mem-reset-control.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/ethernet.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/sdc/sd_cmd_master.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/sdc/sd_cmd_serial_host.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/sdc/sd_data_master.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/sdc/sd_data_serial_host.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/sdc/axi_sdc_controller.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/uart/uart.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/lib/axis/rtl/axis_adapter.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/lib/axis/rtl/axis_async_fifo.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/lib/axis/rtl/axis_async_fifo_adapter.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/axis_gmii_rx.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/axis_gmii_tx.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/eth_mac_1g.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/eth_mac_1g_rgmii.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/eth_mac_1g_rgmii_fifo.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/iddr.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/lfsr.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/oddr.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/rgmii_phy_if.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/ethernet/verilog-ethernet/rtl/ssio_ddr_in.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/board/nexys-video/ethernet-nexys-video.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/srams.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/system-nexys-video.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/synth/riscv.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/hdl/riscv_wrapper.v
    }
      rt::read_verilog -include {
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/sdc
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/f0b6/hdl/verilog
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/35de/hdl/verilog
    /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/c2c6
  } {
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v
      /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/vivado-nexys-video-riscv/nexys-video-riscv.gen/sources_1/bd/riscv/ip/riscv_xlconcat_0_0/synth/riscv_xlconcat_0_0.v
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib xil_defaultlib /home/lic9/prj/HWILCH/HWILCH/ref/vivado-risc-v/workspace/rocket32s2/rocket.vhdl
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top riscv_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-175085-administrator-Precision-3660/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
